$fn=48;
xmove=-1.5;
w=(2-1)*knob_spacing+knob_diameter+wall_thickness*2;
rotate([0,0,0])
	translate([xmove,-w/2,0])
		block(2,4,1,axle_hole=false,reinforcement=true);
rotate([0,0,120])
	translate([xmove,-w/2,0])
		block(2,4,1,axle_hole=false,reinforcement=true);
rotate([0,0,240])
	translate([xmove,-w/2,0])
		block(2,4,1,axle_hole=false,reinforcement=true);
